# Generated by Django 4.1.1 on 2022-09-08 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('closerInspection', models.CharField(default='There is nothing of further interest here', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.object')),
                ('down', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goDown', to='adventure.room')),
                ('east', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goEast', to='adventure.room')),
                ('north', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goNorth', to='adventure.room')),
                ('south', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goSouth', to='adventure.room')),
                ('up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goUp', to='adventure.room')),
                ('west', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goWest', to='adventure.room')),
            ],
            bases=('adventure.object',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.room')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.object')),
                ('weight', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Large'), ('en', 'Enormous')], default='sm', max_length=2)),
                ('heldBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.person')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.room')),
            ],
            bases=('adventure.object',),
        ),
    ]
