# Generated by Django 4.1.1 on 2022-09-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goDown', to='adventure.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='east',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goEast', to='adventure.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='north',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goNorth', to='adventure.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='south',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goSouth', to='adventure.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goUp', to='adventure.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='west',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goWest', to='adventure.room'),
        ),
    ]
